defaults:  # This will "load" everything in the default.yaml, then overwrite with the specific values below
  - default
  - _self_

name: AntonIA_cat
language: catalan
hashtags: "#bondia #alegria #amor"
watermark_path: ./assets/antonIA_cat_watermark.png

publishers:
  - type: instagram
    instagram:
      access_token: ${oc.env:INSTAGRAM_TOKEN}
      instagram_account_id: ${oc.env:ANTONIA_BON_DIA_INSTAGRAM_API_ID}
      base_image_url: ${storage.azure.url}/${storage.azure.container_name}/${storage.azure.base_dir}/