trigger:
  branches:
    include:
      - main
      - development

pr:
  branches:
    include:
      - main
      - development

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'

  - script: |
      python -m pip install poetry
    displayName: 'Install Poetry'

  - script: |
      poetry install --with test
    displayName: 'Install dependencies'

  - script: |
      poetry run pytest --cov=src/test_package --cov-report=xml --cov-report=term
    displayName: 'Run tests with coverage'

  # Publish code coverage results v2
  # Publish any of the code coverage results from a build.
  - task: PublishCodeCoverageResults@2
    inputs:
      summaryFileLocation: 'coverage.xml'
      pathToSources: 'src/test_package'
      failIfCoverageEmpty: true